version: '3'

x-run-mode:
  &default-run-mode
  network_mode: "host"
  privileged: true
  restart: always

services:

  cr-cord:
    <<: *default-run-mode
    image: docker.pkg.github.com/giongto35/cloud-game/cloud-game:dev
    environment:
      - CLOUD_GAME_ENVIRONMENT=prod
      - CLOUD_GAME_COORDINATOR_SERVER_HTTPS=true
      - CLOUD_GAME_COORDINATOR_SERVER_ADDRESS=:80
      - CLOUD_GAME_COORDINATOR_SERVER_TLS_DOMAIN=cloudretro.io
    command: coordinator --v=5
    volumes:
      - /cloud-game/cache:/usr/local/share/cloud-game/assets/cache
      - /cloud-game/games:/usr/local/share/cloud-game/assets/games

  cr-work:
    <<: *default-run-mode
    image: docker.pkg.github.com/giongto35/cloud-game/cloud-game:dev
    environment:
      - CLOUD_GAME_WORKER_SERVER_ADDRESS=:80
      - CLOUD_GAME_WORKER_SERVER_HTTPS=true
      - CLOUD_GAME_WORKER_SERVER_TLS_ADDRESS=:443
      - CLOUD_GAME_WORKER_SERVER_TLS_DOMAIN=cloudretro.io
      - CLOUD_GAME_WORKER_NETWORK_COORDINATORADDRESS=cloudretro.io
      - CLOUD_GAME_WORKER_NETWORK_PUBLICADDRESS=cloudretro.io
      - CLOUD_GAME_WORKER_NETWORK_SECURE=true
      - MESA_GL_VERSION_OVERRIDE=3.3
    entrypoint: [ "/bin/sh", "-c", "/usr/bin/xvfb-run -a $$@", "" ]
    command: worker --v=5 --zone=${ZONE}
    volumes:
      - /cloud-game/cache:/usr/local/share/cloud-game/assets/cache
      - /cloud-game/cores:/usr/local/share/cloud-game/assets/cores
      - /cloud-game/games:/usr/local/share/cloud-game/assets/games
      - /cloud-game/home:/root/.cr
